CREATE TABLE PerformerData (
    id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    performerId INT NOT NULL,
    content TEXT,
    feeds VARCHAR(255),
    likes INT DEFAULT 0,
    dislikes INT DEFAULT 0,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
);